export const adminUi = {
  pageStack: "grid gap-7",
  pageHeader: "flex flex-col gap-3 md:flex-row md:items-end md:justify-between [&_h1]:text-3xl [&_h1]:font-bold [&_h1]:tracking-tight [&_h1]:text-slate-950 [&_p]:max-w-2xl [&_p]:text-sm [&_p]:leading-7 [&_p]:text-slate-600",
  formPanel: "space-y-4 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-200/70 sm:p-6",
  input: "min-h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:bg-white focus:ring-4 focus:ring-emerald-100",
  select: "min-h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-emerald-500 focus:bg-white focus:ring-4 focus:ring-emerald-100",
  textarea: "min-h-30 w-full resize-y rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:bg-white focus:ring-4 focus:ring-emerald-100",
  largeTextarea: "min-h-64",
  fieldGrid: "grid gap-4 md:grid-cols-2",
  formActions: "flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between",
  checkboxField: "flex items-center gap-3 text-sm font-medium text-slate-700 [&_input]:h-4 [&_input]:w-4 [&_input]:accent-emerald-700",
  inlineField: "flex flex-wrap items-center gap-2 text-sm font-medium text-slate-700",
  primaryButton: "inline-flex min-h-11 items-center justify-center rounded-2xl bg-emerald-800 px-5 py-3 text-sm font-semibold text-white shadow-sm shadow-emerald-900/25 transition hover:bg-emerald-900 disabled:cursor-not-allowed disabled:opacity-60",
  logoutButton: "inline-flex min-h-10 items-center justify-center rounded-2xl border border-slate-200 bg-white px-4 py-2 text-sm font-semibold text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60",
  toolPanel: "space-y-4 rounded-2xl border border-emerald-100 bg-emerald-50/70 p-4 [&_strong]:text-slate-900 [&_p]:mt-1 [&_p]:text-sm [&_p]:text-slate-600",
  helperText: "text-sm leading-6 text-slate-500",
  tablePanel: "overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm shadow-slate-200/70",
  table: "min-w-[720px] w-full border-collapse text-left text-sm [&_th]:border-b [&_th]:border-slate-200 [&_th]:bg-slate-50 [&_th]:px-4 [&_th]:py-3 [&_th]:text-xs [&_th]:font-semibold [&_th]:uppercase [&_th]:tracking-wider [&_th]:text-slate-500 [&_td]:border-b [&_td]:border-slate-100 [&_td]:px-4 [&_td]:py-4 [&_td]:align-top [&_td]:text-slate-700",
  accessPanel: "rounded-3xl border border-emerald-100 bg-emerald-50/70 p-5 shadow-sm [&_strong]:text-slate-950",
  roleGrid: "grid gap-3 sm:grid-cols-2",
  roleOption: "flex cursor-pointer items-start gap-3 rounded-2xl border border-slate-200 bg-white p-4 text-sm transition hover:border-emerald-300 hover:bg-emerald-50/50 [&_input]:mt-0.5 [&_input]:h-4 [&_input]:w-4 [&_input]:accent-emerald-700 [&_strong]:block [&_strong]:font-semibold [&_strong]:text-slate-900",
} as const;
